# Generated by Django 3.0 on 2020-01-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VisualizeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calls',
            options={'managed': False},
        ),
    ]
