# Generated by Django 3.0.3 on 2020-03-08 16:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VisualizeApp', '0002_auto_20200128_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.AlterModelTable(
            name='calls',
            table='VisualizeApp_calls',
        ),
    ]
